# Window size
WIDTH, HEIGHT = 1280, 720

# Ball Variables
BALL_RADIUS = 18
BALL_COLOR = (0,0,255)
BALL_VEL = 3

# PADDLE VARIABLES
PADDLE_WIDTH, PADDLE_HEIGHT = 20, 100

# PADDING
LEFT_OFFSET = PADDLE_WIDTH
RIGHT_OFFSET = WIDTH - LEFT_OFFSET

# speed increment factor
SPEED_INCREMENT = 1.3

# Score to min
MAX_SCORE = 5